CREATE TABLE IF NOT EXISTS dim_resource (
    id                            String,
    code                          String,
    name                          String,
    resource_type                 LowCardinality(String),
    resource_category             LowCardinality(Nullable(String)),
    cost_category                 LowCardinality(Nullable(String)),
    unit                          LowCardinality(Nullable(String)),
    parent_id                     Nullable(String),
    calendar_id                   Nullable(String),
    email                         Nullable(String),
    phone                         Nullable(String),
    title                         Nullable(String),
    max_units_per_day             Nullable(Float64),
    default_units_per_time        Nullable(Float64),
    pool_max_available            Nullable(Float64),
    status                        LowCardinality(String),
    hourly_rate                   Nullable(Float64),
    cost_per_use                  Nullable(Float64),
    overtime_rate                 Nullable(Float64),
    sort_order                    Nullable(Int32),
    capacity_spec                 Nullable(String),
    make_model                    Nullable(String),
    quantity_available            Nullable(Int32),
    ownership_type                LowCardinality(Nullable(String)),
    standard_output_per_day       Nullable(Float64),
    fuel_litres_per_hour          Nullable(Decimal(10,2)),
    standard_output_unit          Nullable(String),
    responsible_contractor_id     Nullable(String),
    responsible_contractor_name   Nullable(String),
    wbs_assignment_id             Nullable(String),
    created_at                    DateTime64(3),
    updated_at                    DateTime64(3)
) ENGINE = ReplacingMergeTree(updated_at)
ORDER BY id
SETTINGS index_granularity = 8192;
