CREATE TABLE IF NOT EXISTS fact_risks (
    id                              String,
    project_id                      String,
    code                            String,
    title                           String,
    description                     Nullable(String),
    category_id                     Nullable(String),
    status                          LowCardinality(String),
    risk_type                       LowCardinality(String),
    probability                     LowCardinality(Nullable(String)),
    impact                          LowCardinality(Nullable(String)),
    impact_cost                     Nullable(Int32),
    impact_schedule                 Nullable(Int32),
    risk_score                      Nullable(Float64),
    residual_risk_score             Nullable(Float64),
    rag                             LowCardinality(Nullable(String)),
    trend                           LowCardinality(Nullable(String)),
    owner_id                        Nullable(String),
    identified_by_id                Nullable(String),
    identified_date                 Nullable(Date),
    due_date                        Nullable(Date),
    cost_impact                     Nullable(Decimal(19,2)),
    schedule_impact_days            Nullable(Int32),
    exposure_start_date             Nullable(Date),
    exposure_finish_date            Nullable(Date),
    pre_response_exposure_cost      Nullable(Decimal(19,2)),
    post_response_exposure_cost     Nullable(Decimal(19,2)),
    response_type                   LowCardinality(Nullable(String)),
    post_response_probability       LowCardinality(Nullable(String)),
    post_response_impact_cost       Nullable(Int32),
    post_response_impact_schedule   Nullable(Int32),
    post_response_risk_score        Nullable(Float64),
    created_at                      DateTime64(3),
    updated_at                      DateTime64(3)
) ENGINE = ReplacingMergeTree(updated_at)
ORDER BY id
SETTINGS index_granularity = 8192;
