CREATE TABLE IF NOT EXISTS fact_contracts (
    id                          String,
    project_id                  String,
    tender_id                   Nullable(String),
    contract_number             String,
    loa_number                  Nullable(String),
    contractor_name             String,
    contractor_code             Nullable(String),
    contract_value              Nullable(Decimal(15,2)),
    revised_value               Nullable(Decimal(15,2)),
    loa_date                    Nullable(Date),
    start_date                  Nullable(Date),
    completion_date             Nullable(Date),
    revised_completion_date     Nullable(Date),
    ntp_date                    Nullable(Date),
    actual_completion_date      Nullable(Date),
    dlp_months                  Nullable(Int32),
    ld_rate                     Nullable(Float64),
    status                      LowCardinality(String),
    contract_type               LowCardinality(String),
    description                 Nullable(String),
    currency                    LowCardinality(String),
    mobilisation_advance_pct    Nullable(Decimal(5,2)),
    retention_pct               Nullable(Decimal(5,2)),
    performance_bg_pct          Nullable(Decimal(5,2)),
    payment_terms_days          Nullable(Int32),
    billing_cycle               LowCardinality(Nullable(String)),
    wbs_package_code            Nullable(String),
    package_description         Nullable(String),
    spi                         Nullable(Decimal(6,3)),
    cpi                         Nullable(Decimal(6,3)),
    physical_progress_ai        Nullable(Decimal(5,2)),
    cumulative_ra_bills_crores  Nullable(Decimal(14,2)),
    vo_numbers_issued           Nullable(Int32),
    vo_value_crores             Nullable(Decimal(14,2)),
    performance_score           Nullable(Decimal(5,2)),
    bg_expiry                   Nullable(Date),
    kpi_refreshed_at            Nullable(DateTime64(3)),
    created_at                  DateTime64(3),
    updated_at                  DateTime64(3)
) ENGINE = ReplacingMergeTree(updated_at)
ORDER BY id
SETTINGS index_granularity = 8192;
