package com.bipros.activity.application.dto;

import com.bipros.activity.domain.model.*;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

public record ActivityResponse(
    UUID id,
    String code,
    String name,
    String description,
    UUID projectId,
    UUID wbsNodeId,
    ActivityType activityType,
    DurationType durationType,
    PercentCompleteType percentCompleteType,
    ActivityStatus status,
    Double originalDuration,
    Double remainingDuration,
    Double atCompletionDuration,
    LocalDate plannedStartDate,
    LocalDate plannedFinishDate,
    LocalDate earlyStartDate,
    LocalDate earlyFinishDate,
    LocalDate lateStartDate,
    LocalDate lateFinishDate,
    LocalDate actualStartDate,
    LocalDate actualFinishDate,
    Double totalFloat,
    Double freeFloat,
    Double percentComplete,
    Double physicalPercentComplete,
    Double durationPercentComplete,
    Double unitsPercentComplete,
    UUID calendarId,
    Boolean isCritical,
    LocalDate suspendDate,
    LocalDate resumeDate,
    ConstraintType primaryConstraintType,
    LocalDate primaryConstraintDate,
    ConstraintType secondaryConstraintType,
    LocalDate secondaryConstraintDate,
    Integer sortOrder,
    String notes,
    Long chainageFromM,
    Long chainageToM,
    UUID workActivityId,
    Instant createdAt,
    Instant updatedAt,
    String createdBy,
    String updatedBy
) {
  public static ActivityResponse from(Activity activity) {
    return new ActivityResponse(
        activity.getId(),
        activity.getCode(),
        activity.getName(),
        activity.getDescription(),
        activity.getProjectId(),
        activity.getWbsNodeId(),
        activity.getActivityType(),
        activity.getDurationType(),
        activity.getPercentCompleteType(),
        activity.getStatus(),
        activity.getOriginalDuration(),
        activity.getRemainingDuration(),
        activity.getAtCompletionDuration(),
        activity.getPlannedStartDate(),
        activity.getPlannedFinishDate(),
        activity.getEarlyStartDate(),
        activity.getEarlyFinishDate(),
        activity.getLateStartDate(),
        activity.getLateFinishDate(),
        activity.getActualStartDate(),
        activity.getActualFinishDate(),
        activity.getTotalFloat(),
        activity.getFreeFloat(),
        activity.getPercentComplete(),
        activity.getPhysicalPercentComplete(),
        activity.getDurationPercentComplete(),
        activity.getUnitsPercentComplete(),
        activity.getCalendarId(),
        activity.getIsCritical(),
        activity.getSuspendDate(),
        activity.getResumeDate(),
        activity.getPrimaryConstraintType(),
        activity.getPrimaryConstraintDate(),
        activity.getSecondaryConstraintType(),
        activity.getSecondaryConstraintDate(),
        activity.getSortOrder(),
        activity.getNotes(),
        activity.getChainageFromM(),
        activity.getChainageToM(),
        activity.getWorkActivityId(),
        activity.getCreatedAt(),
        activity.getUpdatedAt(),
        activity.getCreatedBy(),
        activity.getUpdatedBy()
    );
  }
}
